export const SITE = {
  name: "Heimatplatz",
  url: import.meta.env.PUBLIC_SITE_URL ?? "https://heimatplatz.at",
  apiBaseUrl:
    import.meta.env.PUBLIC_API_BASE_URL ?? "https://heimatplatz-api.azurewebsites.net",
  locale: "de_AT",
  language: "de-AT",
  title: "Heimatplatz - Immobilien in Oberösterreich finden",
  titleTemplate: "%s | Heimatplatz",
  description:
    "Heimatplatz buendelt Haeuser, Wohnungen, Grundstuecke und Zwangsversteigerungen in Oberösterreich in einer schnellen, suchmaschinenfreundlichen Web-App.",
  defaultImage: "/og/heimatplatz-default.svg",
  themeColor: "#0a0a0a",
  keywords: [
    "Immobilien Oberösterreich",
    "Immobilien Oberoesterreich",
    "Haus kaufen Oberösterreich",
    "Wohnung kaufen",
    "Haus kaufen",
    "Grundstueck kaufen Oberösterreich",
    "Wohnung kaufen Oberösterreich",
    "Immobilien privat Oberösterreich",
    "Makler Immobilien Oberösterreich",
    "Zwangsversteigerungen",
    "Immobilien Linz",
    "Immobilien Wels",
    "Immobilien Steyr",
    "Immobilien Innviertel",
    "Immobilien Muehlviertel",
    "Immobilien Salzkammergut",
    "Heimatplatz",
  ],
  navigation: [
    { label: "Immobilien", href: "/immobilien/" },
    { label: "Oberösterreich", href: "/immobilien/oberoesterreich/" },
    { label: "ZV", href: "/zwangsversteigerungen/" },
    { label: "Ratgeber", href: "/ratgeber/" },
  ],
} as const;
