using Microsoft.Extensions.DependencyInjection;

namespace Heimatplatz.Core.ApiClient.Configuration;

/// <summary>
/// Extension methods for registering ApiClient services.
/// </summary>
public static class ServiceCollectionExtensions
{
    /// <summary>
    /// Adds the ApiClient feature services.
    /// Registers the generated OpenAPI HTTP handlers for Shiny.Mediator.
    /// </summary>
    public static IServiceCollection AddApiClientFeature(this IServiceCollection services)
    {
        // Configure HttpClient with base URL for API calls
        services.AddHttpClient("Heimatplatz.Core.ApiClient.Generated", client =>
        {
            client.BaseAddress = new Uri("http://localhost:5292");
        });

        // Register the generated OpenAPI HTTP handlers
        // Generated by Shiny.Mediator's OpenApiHttpClientSourceGenerator
        // TODO: Fix OpenAPI spec to include enum definitions for generator
        // services.AddGeneratedOpenApiClient();
        return services;
    }
}
