using Heimatplatz.Api.Core.Data;
using Heimatplatz.Api.Core.Data.Configuration;
using Heimatplatz.Api.Core.Data.Seeding;
using Heimatplatz.Api.Core.Data.Seeding.Configuration;
using Heimatplatz.Api.Core.Email.Configuration;
using Heimatplatz.Api.Features.Admin.Configuration;
using Heimatplatz.Api.Features.Auth.Configuration;
using Heimatplatz.Api.Features.Legal.Configuration;
using Heimatplatz.Api.Features.Locations.Configuration;
using Heimatplatz.Api.Features.Properties.Configuration;
using Heimatplatz.Api.Features.ForeclosureAuctions.Configuration;
using Heimatplatz.Api.Features.Notifications.Configuration;
using Heimatplatz.Api.Features.PropertyImport.Configuration;
using Heimatplatz.Api.Features.AiListing.Configuration;
using Heimatplatz.Api.Features.PropertyDrafts.Configuration;
using Heimatplatz.Api.Features.Telemetry.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using TickerQ.DependencyInjection;
using TickerQ.EntityFrameworkCore.Customizer;
using TickerQ.EntityFrameworkCore.DependencyInjection;

// Feature endpoint namespaces
using Heimatplatz.Api.Features.Admin;
using Heimatplatz.Api.Features.Auth;
using Heimatplatz.Api.Features.Legal;
using Heimatplatz.Api.Features.Locations;
using Heimatplatz.Api.Features.Properties;
using Heimatplatz.Api.Features.ForeclosureAuctions;
using Heimatplatz.Api.Features.Notifications;
using Heimatplatz.Api.Features.PropertyImport;
using Heimatplatz.Api.Features.AiListing;

namespace Heimatplatz.Api.Core.Startup;

public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddApiServices(this IServiceCollection services, IConfiguration configuration)
    {
        // Data (must be before features to register DbContext first)
        services.AddAppData(configuration);
        services.AddDataSeeding();

        // E-Mail-Versand (SMTP wenn konfiguriert, sonst Logging-Fallback)
        services.AddEmailFeature(configuration);

        // HttpContext für Handler, die den authentifizierten User benötigen
        services.AddHttpContextAccessor();

        services.AddShinyMediator();

        // Hintergrund-Jobs (TickerQ, EF-Store im AppDbContext) nur mit echter Datenbank:
        // bei der Build-Zeit-OpenAPI-Generierung und in Integrationstests laeuft der
        // AppDbContext InMemory - dort wuerde der EF-Store scheitern. Features bekommen
        // in dem Fall den No-Op-Scheduler (siehe AddPropertyDraftsFeature).
        var backgroundJobsEnabled = !string.IsNullOrWhiteSpace(configuration.GetConnectionString("DefaultConnection"));
        if (backgroundJobsEnabled)
        {
            services.AddTickerQ(options =>
            {
                // Entity-Konfigurationen registriert AppDbContext.OnModelCreating selbst
                // (IgnoreModelCustomizer), damit Migrations/EnsureCreated beider Provider
                // die Tabellen deterministisch enthalten.
                options.AddOperationalStore(ef =>
                    ef.UseApplicationDbContext<AppDbContext>(ConfigurationType.IgnoreModelCustomizer));
                options.SetExceptionHandler<TickerQJobExceptionHandler>();
            });
        }

        // Features
        services.AddAdminFeature(configuration);
        services.AddAuthFeature();
        services.AddLegalFeature();
        services.AddLocationsFeature();
        services.AddPropertiesFeature();
        services.AddForeclosureAuctionsFeature(configuration);
        services.AddNotificationsFeature(configuration);
        services.AddPropertyImportFeature();
        services.AddAiListingFeature(configuration);
        services.AddPropertyDraftsFeature(backgroundJobsEnabled);
        // OTel-Pipeline + Writer/Retention haengen wie TickerQ am Connection-String-Gate
        services.AddTelemetryFeature(configuration, backgroundJobsEnabled);

        return services;
    }

    public static WebApplication MapEndpoints(this WebApplication app)
    {
        // Feature endpoints (generated by Shiny.Mediator.AspNet)
        // Call each feature's generated endpoints explicitly to avoid ambiguity
        Heimatplatz.Api.Features.Admin.MediatorEndpoints.MapGeneratedMediatorEndpoints(app);
        Heimatplatz.Api.Features.Auth.MediatorEndpoints.MapGeneratedMediatorEndpoints(app);
        Heimatplatz.Api.Features.Legal.MediatorEndpoints.MapGeneratedMediatorEndpoints(app);
        Heimatplatz.Api.Features.Locations.MediatorEndpoints.MapGeneratedMediatorEndpoints(app);
        Heimatplatz.Api.Features.Properties.MediatorEndpoints.MapGeneratedMediatorEndpoints(app);
        Heimatplatz.Api.Features.ForeclosureAuctions.MediatorEndpoints.MapGeneratedMediatorEndpoints(app);
        Heimatplatz.Api.Features.Notifications.MediatorEndpoints.MapGeneratedMediatorEndpoints(app);
        Heimatplatz.Api.Features.PropertyImport.MediatorEndpoints.MapGeneratedMediatorEndpoints(app);
        Heimatplatz.Api.Features.AiListing.MediatorEndpoints.MapGeneratedMediatorEndpoints(app);
        Heimatplatz.Api.Features.PropertyDrafts.MediatorEndpoints.MapGeneratedMediatorEndpoints(app);
        Heimatplatz.Api.Features.Telemetry.MediatorEndpoints.MapGeneratedMediatorEndpoints(app);

        return app;
    }

    /// <summary>
    /// Initialisiert die Datenbank und führt optional Seeding aus.
    /// Basiert auf den DatabaseOptions aus appsettings.{Environment}.json.
    /// </summary>
    public static async Task InitializeDatabaseAsync(this WebApplication app)
    {
        var options = app.Services.GetRequiredService<IOptions<DatabaseOptions>>().Value;
        var configuration = app.Services.GetRequiredService<IConfiguration>();
        var logger = app.Services.GetRequiredService<ILoggerFactory>().CreateLogger("DatabaseInitialization");

        // Validierung: Connection String prüfen
        // Während Build-Tools (z.B. OpenAPI Generator) wird gracefully übersprungen
        var connectionString = configuration.GetConnectionString("DefaultConnection");
        if (string.IsNullOrWhiteSpace(connectionString) || connectionString == "Data Source=:memory:")
        {
            logger.LogWarning(
                "Connection string 'DefaultConnection' is not configured or uses in-memory placeholder. " +
                "Database initialization skipped. This is expected during build/OpenAPI generation.");
            return;
        }

        // Hinweis: KEIN frueher Return mehr wenn AutoMigrate=false und EnableSeeding=false - die
        // essentiellen Referenzdaten-Seeder (ISeeder.IsDemoData=false: Locations, LegalSettings,
        // SellerSources, SystemUser, Backfill) MUESSEN auch dann laufen (z.B. wenn Ops in Produktion
        // auf manuelle Migrations umstellt: Database__AutoMigrate=false, EnableSeeding ist dort
        // ohnehin false). Nur der Migrations-Teil wird ueberhalb per AutoMigrate gesteuert.
        logger.LogInformation("Database initialization started. AutoMigrate={AutoMigrate}, EnableSeeding={EnableSeeding}",
            options.AutoMigrate, options.EnableSeeding);

        // Auto-Migration wenn aktiviert (Development)
        if (options.AutoMigrate)
        {
            logger.LogInformation("Running database migrations...");
            await using var scope = app.Services.CreateAsyncScope();
            var dbContext = scope.ServiceProvider.GetRequiredService<AppDbContext>();

            // ForceRecreate: DB loeschen und neu erstellen (einmaliger Reset)
            if (options.ForceRecreate)
            {
                logger.LogWarning("ForceRecreate=true: Dropping and recreating database...");
                await dbContext.Database.EnsureDeletedAsync();
                await dbContext.Database.EnsureCreatedAsync();
                await SeedMigrationsHistoryAsync(dbContext, logger);
                logger.LogInformation("Database recreated successfully. Set ForceRecreate=false after this.");
            }
            else
            {
                // Strategie:
                //  - DB existiert nicht -> EnsureCreatedAsync (Schema aus Entity-Modell) + History seeden
                //  - DB existiert ohne __EFMigrationsHistory -> Legacy (EnsureCreated) State,
                //    History seeden mit allen Migrations VOR FixProductionSchemaDrift als "applied",
                //    dann fuehrt MigrateAsync den Drift-Fix und alle neueren Migrations idempotent aus
                //  - DB existiert MIT __EFMigrationsHistory -> normaler MigrateAsync-Flow
                logger.LogInformation("Ensuring database and tables exist...");

                if (!await dbContext.Database.CanConnectAsync())
                {
                    logger.LogInformation("Database does not exist, creating from model...");
                    await dbContext.Database.EnsureCreatedAsync();
                    await SeedMigrationsHistoryAsync(dbContext, logger);
                }
                else
                {
                    var hasHistoryTable = await HasMigrationsHistoryTableAsync(dbContext);
                    var hasAppTables = await HasApplicationTablesAsync(dbContext);

                    if (!hasHistoryTable && hasAppTables)
                    {
                        // Legacy DB (EnsureCreatedAsync vorher): Nur die Migrations VOR
                        // FixProductionSchemaDrift als "applied" seeden, damit nachfolgendes
                        // MigrateAsync den Drift-Fix UND alle neueren Migrations idempotent faehrt.
                        logger.LogWarning("Legacy DB detected (tables exist but no __EFMigrationsHistory). Seeding migrations history with all pre-drift migrations as applied.");
                        await SeedMigrationsHistoryAsync(dbContext, logger, markOnlyPreDriftFix: true);
                    }
                    else if (!hasHistoryTable && !hasAppTables)
                    {
                        // DB existiert aber leer (z.B. neu angelegtes Azure SQL ohne Tabellen)
                        logger.LogInformation("Empty database detected, creating from model...");
                        await dbContext.Database.EnsureCreatedAsync();
                        await SeedMigrationsHistoryAsync(dbContext, logger);
                    }

                    logger.LogInformation("Applying pending migrations...");
                    await dbContext.Database.MigrateAsync();
                }
            }
            logger.LogInformation("Database migrations completed.");
        }

        // Seeding: Essentielle Referenzdaten-Seeder (ISeeder.IsDemoData=false, z.B. Locations,
        // Legal-Content, System-User) laufen immer und sind idempotent. Demo-/Test-Seeder
        // (IsDemoData=true) laufen nur bei EnableSeeding=true und werden in Produktion
        // zuverlaessig uebersprungen.
        {
            logger.LogInformation("Running database seeders (EnableSeeding={EnableSeeding})...", options.EnableSeeding);
            using var scope = app.Services.CreateScope();
            var seederRunner = scope.ServiceProvider.GetRequiredService<SeederRunner>();
            await seederRunner.RunAllSeedersAsync(includeDemoData: options.EnableSeeding);
            logger.LogInformation("Database seeding completed.");
        }
    }

    /// <summary>
    /// Prueft ob die __EFMigrationsHistory Tabelle in der aktuellen DB existiert.
    /// Provider-neutral via INFORMATION_SCHEMA / sqlite_master.
    /// </summary>
    private static async Task<bool> HasMigrationsHistoryTableAsync(AppDbContext dbContext)
    {
        try
        {
            // Quoted Identifier: funktioniert unveraendert auf SQLite/SQL Server, verhindert aber
            // dass Postgres den Namen auf "__efmigrationshistory" kleinschreibt und die (per EF
            // Default gross/kleingeschrieben angelegte) Tabelle faelschlich nicht findet.
            await dbContext.Database.ExecuteSqlRawAsync("SELECT 1 FROM \"__EFMigrationsHistory\" WHERE 1=0");
            return true;
        }
        catch
        {
            return false;
        }
    }

    /// <summary>
    /// Prueft ob die Haupt-Anwendungstabellen (Properties) existieren.
    /// </summary>
    private static async Task<bool> HasApplicationTablesAsync(AppDbContext dbContext)
    {
        try
        {
            await dbContext.Database.ExecuteSqlRawAsync("SELECT 1 FROM \"Properties\" WHERE 1=0");
            return true;
        }
        catch
        {
            return false;
        }
    }

    /// <summary>
    /// Seedet __EFMigrationsHistory mit den Namen aller bisherigen Migrations als "applied",
    /// sodass MigrateAsync sie nicht erneut auszufuehren versucht.
    /// Wenn <paramref name="markOnlyPreDriftFix"/>=true, werden nur die Migrations VOR der
    /// "FixProductionSchemaDrift"-Migration markiert - der Drift-Fix und alle neueren
    /// Migrations (z.B. Demo-Daten-Cleanup) laufen dann tatsaechlich via MigrateAsync.
    /// </summary>
    private static async Task SeedMigrationsHistoryAsync(AppDbContext dbContext, ILogger logger, bool markOnlyPreDriftFix = false)
    {
        var migrationsAssembly = dbContext.GetService<IMigrationsAssembly>();
        var allMigrationIds = migrationsAssembly.Migrations.Keys.OrderBy(id => id).ToList();
        if (allMigrationIds.Count == 0) return;

        var idsToMark = allMigrationIds;
        if (markOnlyPreDriftFix)
        {
            var driftFixIndex = allMigrationIds.FindIndex(id => id.Contains("FixProductionSchemaDrift", StringComparison.Ordinal));

            // Fallback: Drift-Fix-Migration nicht gefunden -> wie frueher nur die neueste auslassen
            idsToMark = driftFixIndex >= 0
                ? allMigrationIds.Take(driftFixIndex).ToList()
                : allMigrationIds.Take(allMigrationIds.Count - 1).ToList();
        }

        var productVersion = typeof(Microsoft.EntityFrameworkCore.DbContext).Assembly
            .GetName().Version?.ToString() ?? "10.0.0";

        // Tabelle anlegen wenn fehlt (provider-aware)
        var isSqlServer = dbContext.Database.ProviderName == "Microsoft.EntityFrameworkCore.SqlServer";
        var isPostgres = dbContext.Database.ProviderName == "Npgsql.EntityFrameworkCore.PostgreSQL";
        if (isSqlServer)
        {
            await dbContext.Database.ExecuteSqlRawAsync(@"
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = '__EFMigrationsHistory')
    CREATE TABLE [__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );");
        }
        else
        {
            // Gilt fuer SQLite UND Postgres: beide akzeptieren CREATE TABLE IF NOT EXISTS mit
            // doppelt gequoteten Identifiern.
            await dbContext.Database.ExecuteSqlRawAsync(@"
CREATE TABLE IF NOT EXISTS ""__EFMigrationsHistory"" (
    ""MigrationId"" TEXT NOT NULL CONSTRAINT ""PK___EFMigrationsHistory"" PRIMARY KEY,
    ""ProductVersion"" TEXT NOT NULL
);");
        }

        foreach (var id in idsToMark)
        {
            if (isSqlServer)
            {
                await dbContext.Database.ExecuteSqlRawAsync(
                    "IF NOT EXISTS (SELECT 1 FROM __EFMigrationsHistory WHERE MigrationId = {0}) " +
                    "INSERT INTO __EFMigrationsHistory (MigrationId, ProductVersion) VALUES ({0}, {1})",
                    id, productVersion);
            }
            else if (isPostgres)
            {
                // Postgres kennt kein "INSERT OR IGNORE" (SQLite-Syntax) - ON CONFLICT DO NOTHING
                // ist das Postgres-Aequivalent fuer idempotente Inserts.
                await dbContext.Database.ExecuteSqlRawAsync(
                    "INSERT INTO \"__EFMigrationsHistory\" (\"MigrationId\", \"ProductVersion\") VALUES ({0}, {1}) " +
                    "ON CONFLICT (\"MigrationId\") DO NOTHING",
                    id, productVersion);
            }
            else
            {
                await dbContext.Database.ExecuteSqlRawAsync(
                    "INSERT OR IGNORE INTO __EFMigrationsHistory (MigrationId, ProductVersion) VALUES ({0}, {1})",
                    id, productVersion);
            }
        }

        logger.LogInformation("Seeded __EFMigrationsHistory with {Count} migration(s) marked as applied (markOnlyPreDriftFix={MarkOnlyPreDriftFix}).",
            idsToMark.Count, markOnlyPreDriftFix);
    }
}