using Heimatplatz.Api.Core.Data;
using Heimatplatz.Api.Core.Data.Configuration;
using Heimatplatz.Api.Core.Data.Seeding;
using Heimatplatz.Api.Core.Data.Seeding.Configuration;
using Heimatplatz.Api.Features.Auth.Configuration;
using Heimatplatz.Api.Features.Legal.Configuration;
using Heimatplatz.Api.Features.Locations.Configuration;
using Heimatplatz.Api.Features.Properties.Configuration;
using Heimatplatz.Api.Features.ForeclosureAuctions.Configuration;
using Heimatplatz.Api.Features.Notifications.Configuration;
using Heimatplatz.Api.Features.PropertyImport.Configuration;
using Heimatplatz.Api.Features.SrealListings.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

// Feature endpoint namespaces
using Heimatplatz.Api.Features.Auth;
using Heimatplatz.Api.Features.Legal;
using Heimatplatz.Api.Features.Locations;
using Heimatplatz.Api.Features.Properties;
using Heimatplatz.Api.Features.ForeclosureAuctions;
using Heimatplatz.Api.Features.Notifications;
using Heimatplatz.Api.Features.PropertyImport;
using Heimatplatz.Api.Features.SrealListings;

namespace Heimatplatz.Api.Core.Startup;

public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddApiServices(this IServiceCollection services, IConfiguration configuration)
    {
        // Data (must be before features to register DbContext first)
        services.AddAppData(configuration);
        services.AddDataSeeding();

        // HttpContext für Handler, die den authentifizierten User benötigen
        services.AddHttpContextAccessor();

        services.AddShinyServiceRegistry();
        services.AddShinyMediator();

        // Features
        services.AddAuthFeature();
        services.AddLegalFeature();
        services.AddLocationsFeature();
        services.AddPropertiesFeature();
        services.AddForeclosureAuctionsFeature(configuration);
        services.AddNotificationsFeature(configuration);
        services.AddPropertyImportFeature();
        services.AddSrealListingsFeature(configuration);

        return services;
    }

    public static WebApplication MapEndpoints(this WebApplication app)
    {
        // Feature endpoints (generated by Shiny.Mediator.AspNet)
        // Call each feature's generated endpoints explicitly to avoid ambiguity
        Heimatplatz.Api.Features.Auth.MediatorEndpoints.MapGeneratedMediatorEndpoints(app);
        Heimatplatz.Api.Features.Legal.MediatorEndpoints.MapGeneratedMediatorEndpoints(app);
        Heimatplatz.Api.Features.Locations.MediatorEndpoints.MapGeneratedMediatorEndpoints(app);
        Heimatplatz.Api.Features.Properties.MediatorEndpoints.MapGeneratedMediatorEndpoints(app);
        Heimatplatz.Api.Features.ForeclosureAuctions.MediatorEndpoints.MapGeneratedMediatorEndpoints(app);
        Heimatplatz.Api.Features.Notifications.MediatorEndpoints.MapGeneratedMediatorEndpoints(app);
        Heimatplatz.Api.Features.PropertyImport.MediatorEndpoints.MapGeneratedMediatorEndpoints(app);
        Heimatplatz.Api.Features.SrealListings.MediatorEndpoints.MapGeneratedMediatorEndpoints(app);

        return app;
    }

    /// <summary>
    /// Initialisiert die Datenbank und führt optional Seeding aus.
    /// Basiert auf den DatabaseOptions aus appsettings.{Environment}.json.
    /// </summary>
    public static async Task InitializeDatabaseAsync(this WebApplication app)
    {
        var options = app.Services.GetRequiredService<IOptions<DatabaseOptions>>().Value;
        var configuration = app.Services.GetRequiredService<IConfiguration>();
        var logger = app.Services.GetRequiredService<ILoggerFactory>().CreateLogger("DatabaseInitialization");

        // Validierung: Connection String prüfen
        // Während Build-Tools (z.B. OpenAPI Generator) wird gracefully übersprungen
        var connectionString = configuration.GetConnectionString("DefaultConnection");
        if (string.IsNullOrWhiteSpace(connectionString) || connectionString == "Data Source=:memory:")
        {
            logger.LogWarning(
                "Connection string 'DefaultConnection' is not configured or uses in-memory placeholder. " +
                "Database initialization skipped. This is expected during build/OpenAPI generation.");
            return;
        }

        // Skip database initialization wenn weder Migration noch Seeding aktiviert sind
        if (!options.AutoMigrate && !options.EnableSeeding)
        {
            logger.LogDebug("Database initialization skipped (AutoMigrate=false, EnableSeeding=false).");
            return;
        }

        logger.LogInformation("Database initialization started. AutoMigrate={AutoMigrate}, EnableSeeding={EnableSeeding}",
            options.AutoMigrate, options.EnableSeeding);

        // Auto-Migration wenn aktiviert (Development)
        if (options.AutoMigrate)
        {
            logger.LogInformation("Running database migrations...");
            await using var scope = app.Services.CreateAsyncScope();
            var dbContext = scope.ServiceProvider.GetRequiredService<AppDbContext>();

            // ForceRecreate: DB loeschen und neu erstellen (einmaliger Reset)
            if (options.ForceRecreate)
            {
                logger.LogWarning("ForceRecreate=true: Dropping and recreating database...");
                await dbContext.Database.EnsureDeletedAsync();
                await dbContext.Database.EnsureCreatedAsync();
                logger.LogInformation("Database recreated successfully. Set ForceRecreate=false after this.");
            }
            else
            {
                // Fuer alle DB-Typen: EnsureCreatedAsync verwenden
                // (keine EF Migrations im Projekt - Schema wird aus Code generiert)
                logger.LogInformation("Ensuring database and tables exist...");

                if (!await dbContext.Database.CanConnectAsync())
                {
                    logger.LogInformation("Database does not exist, creating...");
                    await dbContext.Database.EnsureCreatedAsync();
                }
                else
                {
                    // DB existiert - pruefen ob Tabellen vorhanden sind
                    try
                    {
                        // Einfacher Test: Zaehle Eintraege in einer bekannten Tabelle
                        await dbContext.Database.ExecuteSqlRawAsync("SELECT 1 FROM [Properties] WHERE 1=0");
                        logger.LogInformation("Database tables exist.");
                    }
                    catch
                    {
                        // Tabellen fehlen - direkt erstellen auf existierender DB
                        logger.LogWarning("Tables missing, creating tables on existing database...");
                        var creator = dbContext.Database.GetService<Microsoft.EntityFrameworkCore.Storage.IRelationalDatabaseCreator>();
                        try
                        {
                            await creator.CreateTablesAsync();
                            logger.LogInformation("Database tables created successfully.");
                        }
                        catch (Exception createEx)
                        {
                            logger.LogWarning(createEx, "CreateTables failed, trying EnsureDeleted+EnsureCreated...");
                            await dbContext.Database.EnsureDeletedAsync();
                            await dbContext.Database.EnsureCreatedAsync();
                            logger.LogInformation("Database recreated from scratch.");
                        }
                    }
                }
            }
            logger.LogInformation("Database migrations completed.");
        }

        // Seeding: Immer ausfuehren - Seeder sind idempotent und pruefen selbst ob Daten existieren
        {
            logger.LogInformation("Running database seeders...");
            using var scope = app.Services.CreateScope();
            var seederRunner = scope.ServiceProvider.GetRequiredService<SeederRunner>();
            await seederRunner.RunAllSeedersAsync();
            logger.LogInformation("Database seeding completed.");
        }
    }
}